storage:
  dbPath: /var/lib/mongodb
systemLog:
  destination: file
  path: /var/lib/mongodb/mongod.log
  logAppend: true
net:
  bindIp: 0.0.0.0
  port: 5001
processManagement:
  fork: false
security:
  authorization: "disabled"
